import { Category, Customer, ExpenseCategory, Product, School, ShopSettings, Supplier, UniformSet, User } from '@/types';

export const DEFAULT_SHOP_SETTINGS: ShopSettings = {
  shopName: 'Al-Madina Stationery & Uniform Center',
  shopLogo: '',
  ownerName: 'Muhammad Salman',
  phone: '0300-1234567',
  whatsapp: '0300-1234567',
  address: 'Main Bazaar, College Road',
  city: 'Lahore',
  invoiceFooter: 'Thank you for shopping with us! No refund without bill within 7 days.',
  currency: 'PKR',
  currencySymbol: '₨',
  businessTypes: ['stationery', 'uniform', 'bags', 'books', 'general'],
  invoicePrefix: 'INV-',
  nextInvoiceNumber: 1001,
  defaultInvoiceTemplate: 'thermal_80mm',
  showLogoOnInvoice: true,
  showCustomerOnInvoice: true,
  showDiscountOnInvoice: true,
  showProfitOnInvoice: false,
  taxEnabled: false,
  taxPercentage: 0,
  backupLocation: 'C:\\KitabGharBackups',
  autoBackupEnabled: true,
  autoBackupInterval: 'daily',
  lastAutoBackupTime: '',
  preventNegativeStock: true,
  language: 'en',
  theme: 'light',
  setupCompleted: true,
  financialYear: '2026-2027',
};

export const DEFAULT_USERS: User[] = [
  {
    id: 'usr_admin',
    username: 'admin',
    fullName: 'Store Administrator',
    role: 'admin',
    passwordHash: '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', // 'admin' sha256
    phone: '0300-1234567',
    isActive: true,
    createdAt: '2026-01-01T08:00:00.000Z',
  },
  {
    id: 'usr_cashier',
    username: 'cashier1',
    fullName: 'Bilal Cashier',
    role: 'cashier',
    passwordHash: '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
    phone: '0321-9876543',
    isActive: true,
    createdAt: '2026-01-01T08:00:00.000Z',
  }
];

export const DEFAULT_CATEGORIES: Category[] = [
  // Stationery
  {
    id: 'cat_stationery',
    name: 'Stationery',
    nameUrdu: 'اسٹیشنری',
    code: 'STN',
    type: 'stationery',
    subcategories: [
      'Pens', 'Pencils', 'Erasers', 'Sharpeners', 'Rulers', 'Markers', 
      'Highlighters', 'Notebooks', 'Registers', 'Files', 'Folders', 
      'Glue', 'Scissors', 'Colors', 'Art Supplies', 'Geometry Sets', 'Office Supplies'
    ]
  },
  // Uniforms
  {
    id: 'cat_uniforms',
    name: 'School Uniforms',
    nameUrdu: 'اسکول یونیفارم',
    code: 'UNF',
    type: 'uniform',
    subcategories: [
      'School Shirts', 'School Pants', 'School Trousers', 'School Skirts', 
      'School Sweaters', 'School Jerseys', 'School Waistcoats', 'School Caps', 
      'School Ties', 'Belts', 'Socks', 'Uniform Sets', 'Sports Uniforms', 'Other Uniform Items'
    ]
  },
  // School Bags
  {
    id: 'cat_bags',
    name: 'School Bags',
    nameUrdu: 'اسکول بیگز',
    code: 'BAG',
    type: 'bags',
    subcategories: [
      'School Bags', 'Backpacks', 'Trolley Bags', 'Lunch Bags', 'Pencil Cases', 'Bag Accessories'
    ]
  },
  // Books
  {
    id: 'cat_books',
    name: 'Books',
    nameUrdu: 'کتب و نوٹس',
    code: 'BOK',
    type: 'books',
    subcategories: [
      'Textbooks', 'Workbooks', 'Copies', 'Activity Books', 'Guides', 'Islamic & Quran', 'Other Books'
    ]
  },
  // General
  {
    id: 'cat_general',
    name: 'General School Supplies',
    nameUrdu: 'متفرق اشیاء',
    code: 'GEN',
    type: 'general',
    subcategories: ['Water Bottles', 'Lunch Boxes', 'Badges', 'Ribbons', 'Covering Sheets']
  }
];

export const DEFAULT_SCHOOLS: School[] = [
  {
    id: 'sch_1',
    name: 'Army Public School (APS)',
    code: 'APS',
    contactPerson: 'Brig. (R) Asadullah / Head Office',
    phone: '051-9271001',
    whatsapp: '0333-5551122',
    address: 'Mall Road Cantt',
    notes: 'Official green-stripe tie, customized blazer & white shirts with crest.',
    active: true,
    createdAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'sch_2',
    name: 'The City School',
    code: 'TCS',
    contactPerson: 'Ms. Rubina Khan',
    phone: '042-35876611',
    whatsapp: '0321-4447788',
    address: 'Gulberg III Campus',
    notes: 'Navy blue trousers, light sky-blue shirt, red-blue tie.',
    active: true,
    createdAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'sch_3',
    name: 'Beaconhouse School System',
    code: 'BSS',
    contactPerson: 'Mr. Tariq Javed',
    phone: '042-111-232-266',
    whatsapp: '0300-8889911',
    address: 'Canal Road Campus',
    notes: 'Khaki pants / skirts, white polo & collared shirts.',
    active: true,
    createdAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'sch_4',
    name: 'The Educators School',
    code: 'EDU',
    contactPerson: 'Sir Naveed',
    phone: '042-37562211',
    whatsapp: '0312-3334455',
    address: 'Allama Iqbal Town',
    notes: 'Grey trousers, white shirt, maroon tie.',
    active: true,
    createdAt: '2026-01-01T08:00:00.000Z'
  }
];

export const DEFAULT_SUPPLIERS: Supplier[] = [
  {
    id: 'sup_1',
    name: 'National Uniform Manufacturers',
    company: 'National Garments Faisalabad',
    phone: '041-8765432',
    whatsapp: '0300-7654321',
    address: 'Cloth Market, Faisalabad',
    openingBalance: 0,
    currentBalance: 15400,
    notes: 'Primary fabric & uniform manufacturer for shirts, trousers and sweaters.',
    createdAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'sup_2',
    name: 'Punjab Stationery Mart',
    company: 'Punjab Book Depot & Stationery Wholesale',
    phone: '042-37351122',
    whatsapp: '0321-1234455',
    address: 'Urdu Bazaar, Lahore',
    openingBalance: 0,
    currentBalance: 8200,
    notes: 'Wholesale supplier for Dux, Piano, Deer, Dollar and registers.',
    createdAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'sup_3',
    name: 'Champion Bags & Luggage',
    company: 'Champion Bag Industries',
    phone: '052-4261100',
    whatsapp: '0334-9988776',
    address: 'Small Industrial Estate, Sialkot',
    openingBalance: 0,
    currentBalance: 0,
    notes: 'Waterproof school bags, trolleys and lunch pouches.',
    createdAt: '2026-01-01T08:00:00.000Z'
  }
];

export const DEFAULT_CUSTOMERS: Customer[] = [
  {
    id: 'cust_walkin',
    name: 'Walk-in Customer',
    phone: '0300-0000000',
    type: 'walk-in',
    openingBalance: 0,
    currentBalance: 0,
    notes: 'Default customer for fast cash checkout',
    createdAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'cust_1',
    name: 'Tariq Mehmood (Parent)',
    phone: '0321-7788990',
    whatsapp: '0321-7788990',
    address: 'House 45, Street 4, Model Town',
    type: 'regular',
    openingBalance: 0,
    currentBalance: 650, // Credit balance owed to shop
    notes: 'Father of two children at APS Cantt.',
    createdAt: '2026-01-02T10:00:00.000Z'
  },
  {
    id: 'cust_2',
    name: 'Sir Farhan (Beaconhouse Teacher)',
    phone: '0333-4411223',
    whatsapp: '0333-4411223',
    address: 'Staff Colony, Lahore',
    type: 'teacher',
    openingBalance: 0,
    currentBalance: 0,
    notes: 'Entitled to 10% teacher discount on stationery.',
    createdAt: '2026-01-05T12:00:00.000Z'
  },
  {
    id: 'cust_3',
    name: 'Little Angels Grammar School',
    phone: '042-35112244',
    whatsapp: '0301-6677889',
    address: 'Johar Town Phase 2',
    type: 'school',
    openingBalance: 0,
    currentBalance: 12500, // School bulk invoice credit
    notes: 'Orders uniform sets and stationery supplies in bulk each academic session.',
    createdAt: '2026-01-08T14:00:00.000Z'
  }
];

export const DEFAULT_EXPENSE_CATEGORIES: ExpenseCategory[] = [
  { id: 'exp_rent', name: 'Shop Rent', nameUrdu: 'دکان کا کرایہ', isDefault: true },
  { id: 'exp_elec', name: 'Electricity Bill', nameUrdu: 'بجلی کا بل', isDefault: true },
  { id: 'exp_sal', name: 'Staff Salaries', nameUrdu: 'ملازمین کی تنخواہیں', isDefault: true },
  { id: 'exp_trans', name: 'Transport / Freight', nameUrdu: 'کرایہ مال / ٹرانسپورٹ', isDefault: true },
  { id: 'exp_tea', name: 'Tea & Refreshments', nameUrdu: 'چائے و ضیافت', isDefault: true },
  { id: 'exp_net', name: 'Internet & Mobile', nameUrdu: 'انٹرنیٹ و فون', isDefault: true },
  { id: 'exp_pack', name: 'Packaging & Bags', nameUrdu: 'شاپر و پیکنگ', isDefault: true },
  { id: 'exp_rep', name: 'Repair & Maintenance', nameUrdu: 'مرمت و دیکھ بھال', isDefault: true },
  { id: 'exp_misc', name: 'Miscellaneous', nameUrdu: 'متفرق اخراجات', isDefault: true },
];

export const DEFAULT_PRODUCTS: Product[] = [
  // --- STATIONERY ---
  {
    id: 'prod_pen_1',
    name: 'Piano Ballpoint Pen 0.8mm Blue',
    nameUrdu: 'پیانو بال پوائنٹ 0.8 نیلا',
    sku: 'PEN-PIA-BLU',
    barcode: '896400010101',
    type: 'stationery',
    categoryId: 'cat_stationery',
    categoryName: 'Stationery',
    subcategory: 'Pens',
    brand: 'Piano',
    description: 'Smooth writing ballpoint pen for daily school and office work',
    supplierId: 'sup_2',
    supplierName: 'Punjab Stationery Mart',
    unit: 'Piece',
    purchasePrice: 18,
    salePrice: 25,
    wholesalePrice: 20,
    minSalePrice: 20,
    currentStock: 140,
    minStock: 25,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_pen_2',
    name: 'Dollar Pointer Pen Black 0.3mm',
    nameUrdu: 'ڈالر پوائنٹر کالا',
    sku: 'PEN-DOL-BLK',
    barcode: '896400010102',
    type: 'stationery',
    categoryId: 'cat_stationery',
    categoryName: 'Stationery',
    subcategory: 'Pens',
    brand: 'Dollar',
    description: 'Fine point water-based ink pointer pen',
    supplierId: 'sup_2',
    supplierName: 'Punjab Stationery Mart',
    unit: 'Piece',
    purchasePrice: 28,
    salePrice: 40,
    wholesalePrice: 32,
    minSalePrice: 32,
    currentStock: 95,
    minStock: 20,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_penc_1',
    name: 'Deer HB Lead Pencils (Pack of 12)',
    nameUrdu: 'ہرن پنسل پیکٹ (12 عدد)',
    sku: 'PNC-DER-12',
    barcode: '896400010103',
    type: 'stationery',
    categoryId: 'cat_stationery',
    categoryName: 'Stationery',
    subcategory: 'Pencils',
    brand: 'Deer',
    description: 'Standard wooden HB writing pencils pack of 12 with eraser tips',
    supplierId: 'sup_2',
    supplierName: 'Punjab Stationery Mart',
    unit: 'Pack',
    purchasePrice: 180,
    salePrice: 250,
    wholesalePrice: 210,
    minSalePrice: 220,
    currentStock: 45,
    minStock: 10,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_eras_1',
    name: 'Dux Dust-Free Eraser Medium',
    nameUrdu: 'ڈکس ایریزر (مٹانے والا)',
    sku: 'ERS-DUX-MED',
    barcode: '896400010104',
    type: 'stationery',
    categoryId: 'cat_stationery',
    categoryName: 'Stationery',
    subcategory: 'Erasers',
    brand: 'Dux',
    description: 'High grade non-smudge soft eraser',
    supplierId: 'sup_2',
    supplierName: 'Punjab Stationery Mart',
    unit: 'Piece',
    purchasePrice: 12,
    salePrice: 20,
    wholesalePrice: 15,
    minSalePrice: 15,
    currentStock: 80,
    minStock: 15,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_geom_1',
    name: 'Dux Oxford Mathematical Geometry Box',
    nameUrdu: 'ڈکس جیومیٹری باکس',
    sku: 'GEO-DUX-BOX',
    barcode: '896400010105',
    type: 'stationery',
    categoryId: 'cat_stationery',
    categoryName: 'Stationery',
    subcategory: 'Geometry Sets',
    brand: 'Dux',
    description: 'Complete metal geometry set with precision compass, divider, and ruler set',
    supplierId: 'sup_2',
    supplierName: 'Punjab Stationery Mart',
    unit: 'Piece',
    purchasePrice: 280,
    salePrice: 380,
    wholesalePrice: 320,
    minSalePrice: 330,
    currentStock: 32,
    minStock: 8,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_reg_1',
    name: 'Hardcover School Notebook 200 Pages (Four Lines)',
    nameUrdu: 'اسکول کاپی چار لائن 200 صفحہ',
    sku: 'NOT-4LN-200',
    barcode: '896400010106',
    type: 'stationery',
    categoryId: 'cat_stationery',
    categoryName: 'Stationery',
    subcategory: 'Notebooks',
    brand: 'Eagle',
    description: 'High grade 70gsm paper four lines notebook for English',
    supplierId: 'sup_2',
    supplierName: 'Punjab Stationery Mart',
    unit: 'Piece',
    purchasePrice: 120,
    salePrice: 170,
    wholesalePrice: 140,
    minSalePrice: 150,
    currentStock: 110,
    minStock: 25,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },

  // --- UNIFORMS WITH SPECIAL VARIANTS (SIZES, GENDER, COLORS, SCHOOLS) ---
  {
    id: 'prod_unf_aps_shirt',
    name: 'APS White School Shirt',
    nameUrdu: 'آرمی پبلک اسکول سفید قمیض',
    sku: 'APS-SHIRT',
    barcode: '896400020001',
    type: 'uniform',
    categoryId: 'cat_uniforms',
    categoryName: 'School Uniforms',
    subcategory: 'School Shirts',
    brand: 'National',
    description: 'Official Army Public School white cotton-blend shirt with collar stitching and button cuffs',
    supplierId: 'sup_1',
    supplierName: 'National Uniform Manufacturers',
    schoolId: 'sch_1',
    schoolName: 'Army Public School (APS)',
    unit: 'Piece',
    purchasePrice: 550,
    salePrice: 850,
    wholesalePrice: 700,
    minSalePrice: 750,
    currentStock: 45, // Sum of variants below
    minStock: 10,
    isActive: true,
    hasVariants: true,
    variants: [
      {
        id: 'var_aps_sh_28',
        productId: 'prod_unf_aps_shirt',
        sku: 'APS-SH-WHT-28',
        barcode: '896400020128',
        schoolId: 'sch_1',
        schoolName: 'Army Public School (APS)',
        size: '28',
        color: 'White',
        gender: 'boy',
        purchasePrice: 500,
        salePrice: 800,
        wholesalePrice: 650,
        minSalePrice: 700,
        currentStock: 15,
        minStock: 4
      },
      {
        id: 'var_aps_sh_30',
        productId: 'prod_unf_aps_shirt',
        sku: 'APS-SH-WHT-30',
        barcode: '896400020130',
        schoolId: 'sch_1',
        schoolName: 'Army Public School (APS)',
        size: '30',
        color: 'White',
        gender: 'boy',
        purchasePrice: 550,
        salePrice: 850,
        wholesalePrice: 700,
        minSalePrice: 750,
        currentStock: 22,
        minStock: 5
      },
      {
        id: 'var_aps_sh_32',
        productId: 'prod_unf_aps_shirt',
        sku: 'APS-SH-WHT-32',
        barcode: '896400020132',
        schoolId: 'sch_1',
        schoolName: 'Army Public School (APS)',
        size: '32',
        color: 'White',
        gender: 'boy',
        purchasePrice: 600,
        salePrice: 900,
        wholesalePrice: 750,
        minSalePrice: 800,
        currentStock: 8,
        minStock: 3
      }
    ],
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_unf_aps_pant',
    name: 'APS Grey School Trouser / Pant',
    nameUrdu: 'آرمی پبلک اسکول گرے پینٹ',
    sku: 'APS-PANT',
    barcode: '896400020002',
    type: 'uniform',
    categoryId: 'cat_uniforms',
    categoryName: 'School Uniforms',
    subcategory: 'School Pants',
    brand: 'National',
    description: 'Army Public School charcoal grey pleated school pants with pockets and elastic adjustment',
    supplierId: 'sup_1',
    supplierName: 'National Uniform Manufacturers',
    schoolId: 'sch_1',
    schoolName: 'Army Public School (APS)',
    unit: 'Piece',
    purchasePrice: 650,
    salePrice: 950,
    wholesalePrice: 800,
    minSalePrice: 850,
    currentStock: 35,
    minStock: 10,
    isActive: true,
    hasVariants: true,
    variants: [
      {
        id: 'var_aps_pt_28',
        productId: 'prod_unf_aps_pant',
        sku: 'APS-PT-GRY-28',
        barcode: '896400020228',
        schoolId: 'sch_1',
        schoolName: 'Army Public School (APS)',
        size: '28',
        color: 'Grey',
        gender: 'boy',
        purchasePrice: 600,
        salePrice: 900,
        wholesalePrice: 750,
        minSalePrice: 800,
        currentStock: 14,
        minStock: 4
      },
      {
        id: 'var_aps_pt_30',
        productId: 'prod_unf_aps_pant',
        sku: 'APS-PT-GRY-30',
        barcode: '896400020230',
        schoolId: 'sch_1',
        schoolName: 'Army Public School (APS)',
        size: '30',
        color: 'Grey',
        gender: 'boy',
        purchasePrice: 650,
        salePrice: 950,
        wholesalePrice: 800,
        minSalePrice: 850,
        currentStock: 15,
        minStock: 4
      },
      {
        id: 'var_aps_pt_32',
        productId: 'prod_unf_aps_pant',
        sku: 'APS-PT-GRY-32',
        barcode: '896400020232',
        schoolId: 'sch_1',
        schoolName: 'Army Public School (APS)',
        size: '32',
        color: 'Grey',
        gender: 'boy',
        purchasePrice: 700,
        salePrice: 1000,
        wholesalePrice: 850,
        minSalePrice: 900,
        currentStock: 6,
        minStock: 3
      }
    ],
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_unf_aps_tie',
    name: 'APS Official School Tie',
    nameUrdu: 'آرمی پبلک اسکول ٹائی',
    sku: 'APS-TIE-01',
    barcode: '896400020003',
    type: 'uniform',
    categoryId: 'cat_uniforms',
    categoryName: 'School Uniforms',
    subcategory: 'School Ties',
    brand: 'National',
    description: 'Official APS green & yellow striped woven necktie with embroidered logo',
    supplierId: 'sup_1',
    supplierName: 'National Uniform Manufacturers',
    schoolId: 'sch_1',
    schoolName: 'Army Public School (APS)',
    unit: 'Piece',
    purchasePrice: 120,
    salePrice: 200,
    wholesalePrice: 160,
    minSalePrice: 170,
    currentStock: 50,
    minStock: 10,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_unf_aps_belt',
    name: 'APS Official School Belt',
    nameUrdu: 'آرمی پبلک اسکول بیلٹ',
    sku: 'APS-BLT-01',
    barcode: '896400020004',
    type: 'uniform',
    categoryId: 'cat_uniforms',
    categoryName: 'School Uniforms',
    subcategory: 'Belts',
    brand: 'National',
    description: 'Black elastic school belt with APS metal brass buckle',
    supplierId: 'sup_1',
    supplierName: 'National Uniform Manufacturers',
    schoolId: 'sch_1',
    schoolName: 'Army Public School (APS)',
    unit: 'Piece',
    purchasePrice: 90,
    salePrice: 150,
    wholesalePrice: 120,
    minSalePrice: 130,
    currentStock: 40,
    minStock: 10,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_unf_tcs_shirt',
    name: 'City School Sky-Blue Shirt',
    nameUrdu: 'دی سٹی اسکول آسمانی قمیض',
    sku: 'TCS-SHIRT',
    barcode: '896400020005',
    type: 'uniform',
    categoryId: 'cat_uniforms',
    categoryName: 'School Uniforms',
    subcategory: 'School Shirts',
    brand: 'National',
    description: 'The City School official light blue cotton dress shirt',
    supplierId: 'sup_1',
    supplierName: 'National Uniform Manufacturers',
    schoolId: 'sch_2',
    schoolName: 'The City School',
    unit: 'Piece',
    purchasePrice: 580,
    salePrice: 880,
    wholesalePrice: 720,
    minSalePrice: 750,
    currentStock: 30,
    minStock: 8,
    isActive: true,
    hasVariants: true,
    variants: [
      {
        id: 'var_tcs_sh_28',
        productId: 'prod_unf_tcs_shirt',
        sku: 'TCS-SH-BLU-28',
        barcode: '896400020528',
        schoolId: 'sch_2',
        schoolName: 'The City School',
        size: '28',
        color: 'Sky Blue',
        gender: 'unisex',
        purchasePrice: 550,
        salePrice: 850,
        wholesalePrice: 700,
        minSalePrice: 750,
        currentStock: 12,
        minStock: 4
      },
      {
        id: 'var_tcs_sh_30',
        productId: 'prod_unf_tcs_shirt',
        sku: 'TCS-SH-BLU-30',
        barcode: '896400020530',
        schoolId: 'sch_2',
        schoolName: 'The City School',
        size: '30',
        color: 'Sky Blue',
        gender: 'unisex',
        purchasePrice: 580,
        salePrice: 880,
        wholesalePrice: 720,
        minSalePrice: 780,
        currentStock: 18,
        minStock: 4
      }
    ],
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },

  // --- SCHOOL BAGS WITH VARIANTS (BRAND, MODEL, COLOR, SIZE) ---
  {
    id: 'prod_bag_1',
    name: 'Kids Ergonomic School Bag (Lightweight Waterproof)',
    nameUrdu: 'بچوں کا اسکول بیگ واٹر پروف',
    sku: 'BAG-KID-ERG',
    barcode: '896400030001',
    type: 'bags',
    categoryId: 'cat_bags',
    categoryName: 'School Bags',
    subcategory: 'School Bags',
    brand: 'Champion',
    description: 'High endurance padded shoulder straps with double bottle pocket and multi-compartment organizers',
    supplierId: 'sup_3',
    supplierName: 'Champion Bags & Luggage',
    unit: 'Piece',
    purchasePrice: 1200,
    salePrice: 1850,
    wholesalePrice: 1500,
    minSalePrice: 1600,
    currentStock: 24,
    minStock: 5,
    isActive: true,
    hasVariants: true,
    variants: [
      {
        id: 'var_bag_blu_m',
        productId: 'prod_bag_1',
        sku: 'BAG-ERG-BLU-M',
        barcode: '896400030101',
        model: 'Explorer Ergonomic',
        color: 'Navy Blue',
        size: 'Medium (Class 1-4)',
        purchasePrice: 1200,
        salePrice: 1850,
        wholesalePrice: 1500,
        minSalePrice: 1600,
        currentStock: 14,
        minStock: 3
      },
      {
        id: 'var_bag_red_m',
        productId: 'prod_bag_1',
        sku: 'BAG-ERG-RED-M',
        barcode: '896400030102',
        model: 'Explorer Ergonomic',
        color: 'Crimson Red',
        size: 'Medium (Class 1-4)',
        purchasePrice: 1200,
        salePrice: 1850,
        wholesalePrice: 1500,
        minSalePrice: 1600,
        currentStock: 10,
        minStock: 2
      }
    ],
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_bag_2',
    name: 'Trolley Wheels School Backpack (Heavy Duty)',
    nameUrdu: 'پہیوں والا اسکول ٹرالی بیگ',
    sku: 'BAG-TRL-HD',
    barcode: '896400030002',
    type: 'bags',
    categoryId: 'cat_bags',
    categoryName: 'School Bags',
    subcategory: 'Trolley Bags',
    brand: 'Champion',
    description: 'Trolley wheels convertible backpack for heavy books with aluminum telescopic handle',
    supplierId: 'sup_3',
    supplierName: 'Champion Bags & Luggage',
    unit: 'Piece',
    purchasePrice: 2200,
    salePrice: 3200,
    wholesalePrice: 2600,
    minSalePrice: 2800,
    currentStock: 8,
    minStock: 2,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },

  // --- BOOKS ---
  {
    id: 'prod_bk_1',
    name: 'Oxford New Countdown Book 3 (Third Edition)',
    nameUrdu: 'آکسفورڈ نیو کاؤنٹ ڈاؤن ریاضی 3',
    sku: 'BK-OXF-MAT3',
    barcode: '896400040001',
    type: 'books',
    categoryId: 'cat_books',
    categoryName: 'Books',
    subcategory: 'Textbooks',
    brand: 'Oxford University Press',
    description: 'Primary level mathematics textbook prescribed across leading schools',
    supplierId: 'sup_2',
    supplierName: 'Punjab Stationery Mart',
    unit: 'Piece',
    purchasePrice: 480,
    salePrice: 580,
    wholesalePrice: 510,
    minSalePrice: 540,
    currentStock: 25,
    minStock: 5,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  },
  {
    id: 'prod_bk_2',
    name: 'Punjab Curriculum Textbook Urdu Class 5',
    nameUrdu: 'پنجاب ٹیکسٹ بک اردو جماعت پنجم',
    sku: 'BK-PTB-URD5',
    barcode: '896400040002',
    type: 'books',
    categoryId: 'cat_books',
    categoryName: 'Books',
    subcategory: 'Textbooks',
    brand: 'PCTB',
    description: 'Standard provincial curriculum Urdu book class 5',
    supplierId: 'sup_2',
    supplierName: 'Punjab Stationery Mart',
    unit: 'Piece',
    purchasePrice: 160,
    salePrice: 210,
    wholesalePrice: 180,
    minSalePrice: 190,
    currentStock: 38,
    minStock: 8,
    isActive: true,
    hasVariants: false,
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-01-01T08:00:00.000Z'
  }
];

export const DEFAULT_UNIFORM_SETS: UniformSet[] = [
  {
    id: 'set_aps_summer_30',
    name: 'APS Summer Uniform Kit (Size 30)',
    nameUrdu: 'اے پی ایس سمر یونیفارم کٹ (سائز 30)',
    schoolId: 'sch_1',
    schoolName: 'Army Public School (APS)',
    season: 'summer',
    description: 'Complete summer school set including 1 Shirt, 1 Trouser, 1 Tie, and 1 Belt for APS students.',
    sku: 'APS-KIT-SUM-30',
    barcode: '896400090001',
    setPrice: 2000, // Discounted bundle price (Individual total: 850 + 950 + 200 + 150 = 2150)
    components: [
      {
        productId: 'prod_unf_aps_shirt',
        variantId: 'var_aps_sh_30',
        productName: 'APS White School Shirt',
        variantLabel: 'Size 30, White',
        quantity: 1
      },
      {
        productId: 'prod_unf_aps_pant',
        variantId: 'var_aps_pt_30',
        productName: 'APS Grey School Trouser / Pant',
        variantLabel: 'Size 30, Grey',
        quantity: 1
      },
      {
        productId: 'prod_unf_aps_tie',
        productName: 'APS Official School Tie',
        quantity: 1
      },
      {
        productId: 'prod_unf_aps_belt',
        productName: 'APS Official School Belt',
        quantity: 1
      }
    ],
    active: true,
    createdAt: '2026-01-01T08:00:00.000Z'
  }
];
